# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
#  - pinned
#  - security
# Label to use when marking an issue as stale
staleLabel: expirado
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Issue cerrado automáticamente después de un período de inactividad.
  Si la oportunidad aún está abierta, se puede crear un nuevo issue con una descripción actualizada.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
